import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import SEO from '../components/SEO.jsx';

export default function LandingCard() {
  const { id } = useParams();
  const [state, setState] = useState({ loading: true, card: null, error: null });

  useEffect(() => {
    let alive = true;
    setState({ loading: true, card: null, error: null });
    fetch(`/api/landing-cards/${encodeURIComponent(id)}`, { cache: 'no-store' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((d) => { if (alive) setState({ loading: false, card: d, error: null }); })
      .catch((e) => { if (alive) setState({ loading: false, card: null, error: e.message }); });
    return () => { alive = false; };
  }, [id]);

  const payload = state.card?.payload || {};

  return (
    <>
      <SEO
        title={payload.callsign ? `${payload.callsign} Landing Report — OPS ROOM` : 'Landing Report — OPS ROOM'}
        description="A shared OPS ROOM landing report card: landing rate, touchdown G and speed, flight result and the final approach profile."
        path={`f/${id}`}
      />
      <section className="section" style={{ minHeight: '70vh' }}>
        <div className="container" style={{ maxWidth: '920px' }}>
          <span className="section-eyebrow" style={{ justifyContent: 'center', display: 'flex' }}>
            / SHARED LANDING REPORT
          </span>
          <h1 style={{ textAlign: 'center', fontFamily: 'var(--font-mono)', margin: '1rem 0 2rem' }}>
            {payload.callsign || 'LANDING REPORT'}
          </h1>

          {state.loading && (
            <div style={{ textAlign: 'center', color: 'var(--fg-soft)' }}>LOADING CARD...</div>
          )}

          {state.error && (
            <div style={{ textAlign: 'center', color: 'var(--fg-soft)', marginBottom: '2rem' }}>
              <p style={{ color: 'var(--fg-soft)' }}>
                This card is not available. Landing reports stay private unless the pilot chose to share them from the
                OPS ROOM app.
              </p>
              <Link to="/" className="btn btn-primary" style={{ marginTop: '1rem' }}>Return to Dispatch</Link>
            </div>
          )}

          {state.card?.html && (
            <div
              dangerouslySetInnerHTML={{ __html: state.card.html }}
              style={{ overflow: 'auto', borderRadius: '8px' }}
            />
          )}

          {!state.loading && !state.error && state.card?.html && (
            <div style={{ textAlign: 'center', margin: '2rem 0' }}>
              <p style={{ color: 'var(--fg-soft)', fontSize: '0.9rem' }}>
                Flight data only. Generated by <strong>OPS ROOM</strong>, a free operations suite for MSFS 2020 and
                MSFS 2024.
              </p>
              <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'center', flexWrap: 'wrap' }}>
                <Link to="/" className="btn btn-primary">OPS ROOM</Link>
                <Link to="/features" className="btn">Browse Modules</Link>
              </div>
            </div>
          )}
        </div>
      </section>
    </>
  );
}
